lidar_topic: /livox/lidar
imu_topic: /livox/imu

map_frame: map
body_frame: body

publish_voxel_map: true
publish_voxel_num: 2000


scan_resolution: 0.1
voxel_size: 0.2
# voxel_size: 0.4
map_capacity: 100000
max_point_thresh: 100
update_size_threshes: 20
merge_thresh_for_angle: 0.2
merge_thresh_for_distance: 0.04


use_offline_rosbag: true          # use offline rosbag
offline_rosbag_file: /home/larry/featVoxelMap_ws/data/jyl-office.bag


model_file: /home/larry/codeGit/implict_voxel/src/feat_voxel_map/checkpoint/best_voxel.pt
init_time: 2.0        # wait how many seconds to init the map.
valid_weight_threshold: 0.799     # when predicting p2v, only p2v's weight > this threshold are choosen
batch_size: 4
prediction_skip: 1                # how many point do one prediction? 1: every point; 2: half point.